const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.TWINTRADE_CHROME?{executablePath:process.env.TWINTRADE_CHROME}:{}),args:['--no-sandbox']});
 const errors=[];const page=await browser.newPage({viewport:{width:393,height:852}});page.on('pageerror',e=>errors.push(e.message));
 // Valid empty trader snapshots prevent unrelated offline retry notices from racing timer assertions.
 await page.route('https://**/*',r=>r.request().url().includes('/open-trades')?r.fulfill({json:[]}):r.abort());await page.addInitScript(()=>{window.WebSocket=class{constructor(url){this.readyState=1;this.url=url;if(url.includes('backend-pricing'))setTimeout(()=>this.onmessage?.({data:JSON.stringify({m:[0,84610,1,2682,300,84610,313,2682],i:[0,84612,1,2683],t:Date.now()})}),500)}close(){this.readyState=3}send(){}};});
 await page.goto('file://'+path.resolve('dist/TwinTrade.html'));await page.waitForTimeout(1100);
 assert.equal(await page.locator('#price').textContent(),'$84610.00');await page.click('#long');await page.waitForTimeout(300);assert((await page.locator('#positions').textContent()).includes('L'));
 // Combined BTC restores 500× through the actual DEGEN market, and owns
 // entry / LIQ tags remain on the BTC chart even without public overlays.
 await page.evaluate(()=>{window.ownLabels=[];const proto=CanvasRenderingContext2D.prototype,original=proto.fillText;proto.fillText=function(text,x,y,...rest){ownLabels.push({text,y});return original.call(this,text,x,y,...rest)};});
 await page.selectOption('#lev','500');await page.click('#long');await page.waitForTimeout(300);
 assert.equal(await page.evaluate(()=>book.positions.at(-1).pair),300);assert.equal(await page.evaluate(()=>book.positions.at(-1).lev),500);assert((await page.locator('#positions').textContent()).includes('BTCDEGEN'));assert((await page.locator('#quote').textContent()).includes('Order BTCDEGEN'));
 await page.evaluate(()=>{$('overlay').checked=false;draw();});assert(await page.evaluate(()=>ownLabels.some(o=>o.text.startsWith('L LIQ D')&&o.y>=0&&o.y<=$('chart').getBoundingClientRect().height)),'own BTCDEGEN LIQ remains visible on BTC');await page.evaluate(()=>{$('overlay').checked=true;});await page.selectOption('#lev','200');
 for(const [w,h]of [[393,852],[852,393],[360,640],[740,360],[393,852]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(150);
 const chartBefore=await page.locator('#chart').boundingBox();
 await page.evaluate(()=>setLoadBar(100,'1248 open trades synced'));
 const chartDuring=await page.locator('#chart').boundingBox();assert.deepEqual(chartDuring,chartBefore,'sync message must not shift/resize chart');
 await page.evaluate(()=>{loadingTasks.clear();loadingProgress('history',25,'History 1/4 pages');loadingProgress('traders',60,'POLYGON 60/100');});
 assert.equal(await page.locator('#loadingProgress').isVisible(),true);assert((await page.locator('#loadingDetails').textContent()).includes('History 1/4 pages'));
 assert.deepEqual(await page.locator('#chart').boundingBox(),chartBefore,'progress overlay keeps chart fixed');
 const progressBox=await page.locator('#loadingProgress').boundingBox();assert(progressBox.y>=chartBefore.y&&progressBox.y<chartBefore.y+5,'progress is at chart top');
 await page.evaluate(()=>{loadingProgress('history',100,'History ready',true);});assert((await page.locator('#loadingDetails').textContent()).includes('POLYGON 60/100'));
 await page.evaluate(()=>{loadingProgress('traders',100,'Traders ready',true);});
 const messageBox=await page.locator('#syncMessage').boundingBox(),feesBox=await page.locator('#fees').boundingBox();assert(messageBox.y+messageBox.height<=feesBox.y+1,'sync message above borrowing text');
 await page.evaluate(()=>setLoadBar(100,''));assert.deepEqual(await page.locator('#chart').boundingBox(),chartBefore,'clearing message keeps chart fixed');await page.screenshot({path:'build/mobile-qa.png'});for(const id of ['menu','settings','long','short']){const b=await page.locator('#'+id).boundingBox();assert(b&&b.x>=0&&b.y>=0&&b.x+b.width<=w+1&&b.y+b.height<=h+1,`${id} outside ${w}x${h}: ${JSON.stringify(b)}`)}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No horizontal overflow');}
 await page.evaluate(()=>setLoadBar(100,'Trades synced'));await page.waitForTimeout(2200);await page.evaluate(()=>setLoadBar(100,'New trades synced'));await page.waitForTimeout(1500);assert.equal(await page.locator('#syncMessage').isVisible(),true,'old timer does not clear new sync text');await page.waitForTimeout(2100);assert.equal(await page.locator('#syncMessage').isVisible(),false,'completed sync text expires');
 // Frequent backend refreshes and failed history retries must stay silent.
 await page.evaluate(async()=>{loadingTasks.clear();clearTimeout(progressHideT);$('loadingProgress').hidden=true;for(let i=0;i<3;i++){await loadHistory();await loadPublicSnapshot();}});
 assert.equal(await page.locator('#loadingProgress').isVisible(),false,'routine refresh cannot resurrect progress');
 await page.evaluate(()=>$('retryPublic').onclick());await page.waitForFunction(()=>!snapshotBusy);assert.equal(await page.locator('#loadingProgress').isVisible(),true,'manual Reload still shows progress');
 await page.evaluate(()=>{view={span:250,off:15,yOff:2};selectedPublic='test'});await page.click('#zoomMenu');await page.click('#resetChart');await page.click('#zoomMenu');assert.deepEqual(await page.evaluate(()=>({...view,selectedPublic})),{span:75,off:0,yOff:0,selectedPublic:null});
 await page.click('#menu');await page.click('#portfolioOpen');assert.equal(await page.locator('#accountPanel').isVisible(),true);assert((await page.locator('#accountRows').textContent()).includes('L'));await page.click('#accountHistory');assert((await page.locator('#accountTitle').textContent()).includes('Past trades'));await page.click('#closeAccount');
 await page.evaluate(()=>{last[0]=Date.now()-30000;renderSyncStatus()});assert.equal(await page.locator('#desync').isVisible(),true);await page.evaluate(()=>{last[0]=Date.now();renderSyncStatus()});assert.equal(await page.locator('#desync').isVisible(),false);
 await page.evaluate(()=>{last[0]=Date.now()-29900;renderSyncStatus()});assert.equal(await page.locator('#desync').isVisible(),false);
 await page.evaluate(()=>{publicTrades=[{id:'test',isOpen:true,kind:'public',net:'POLYGON',pair:0,long:true,lev:100,amount:10,entry:84000,liq:83000}];renderPublic()});await page.click('#statsOpen');assert.equal(await page.locator('#statsPanel').isVisible(),true);assert((await page.locator('#statsRows').textContent()).includes('$84000.00'));assert((await page.locator('#statsRows').textContent()).includes('$83000.00'));
 await page.evaluate(()=>{publicTrades[0].entry=85000;renderPublic();renderStats()});assert((await page.locator('#statsRows').textContent()).includes('$85000.00'));for(const [w,h]of [[360,640],[740,360]]){await page.setViewportSize({width:w,height:h});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)}await page.evaluate(()=>{publicTrades[0].liq=undefined;renderPublic();renderStats()});assert((await page.locator('#statsRows').textContent()).includes('EST'));assert((await page.locator('#statsRows').textContent()).includes('$84235.00'));assert((await page.locator('#statsRows').textContent()).includes('1 estimated'));
 await page.evaluate(()=>{const now=Date.now();candles[0]=[{t:now,o:84000,h:86000,l:83000,c:85000}];prices[0]=85000;window.avgTexts=[];const ctx=document.getElementById('chart').getContext('2d'),old=ctx.fillText.bind(ctx);ctx.fillText=(s,...a)=>{avgTexts.push(s);old(s,...a)};draw()});assert((await page.evaluate(()=>avgTexts)).some(s=>s.includes('AVG LIQ EST L ALL')&&s.includes('$84235.00')),'all-leverage estimate stroked and labeled');
 await page.click('#closeStats');assert.equal(await page.locator('#statsPanel').isVisible(),false);await page.setViewportSize({width:393,height:852});
 assert.equal(await page.evaluate(()=>typeof checkDanger),'undefined');assert.equal(await page.evaluate(()=>safeLiq({kind:'live',liq:83000})),83000);
 // A profitable price move can still have negative net P&L; own labels must agree.
 await page.evaluate(()=>{const now=Date.now();mode='paper';pair=0;prices[0]=84670.18;last[0]=now;const p=Engine.open(0,true,100,200,84631.5684,{fee:.035,slip:.005,borrow:0,funding:0,liq:90},now);book={cash:0,positions:[p],history:[]};const ctx=document.getElementById('chart').getContext('2d');window.chartTexts=[];const old=ctx.fillText.bind(ctx);ctx.fillText=(s,...args)=>{chartTexts.push(s);old(s,...args)};candles[0]=[{t:Math.floor(now/60000)*60000,o:84630,h:84680,l:84620,c:84670.18,source:'gains-live'}];render();});
 const feeCheck=await page.evaluate(()=>({card:document.getElementById('positions').textContent,labels:chartTexts,net:'-$'+Math.abs(Engine.value(book.positions[0],prices[0]).net).toFixed(2)}));
 assert(feeCheck.card.includes('Open fee $7.00'));assert(feeCheck.card.includes('Close est. $7.00'));assert(feeCheck.labels.some(s=>s.includes(' NET')));assert(feeCheck.labels.includes(feeCheck.net),'own chart label shows net, not gross');
 await page.evaluate(()=>{const now=Date.now();book.positions=[Engine.open(0,false,100,200,84670.18,{fee:.035,slip:0,borrow:.001,funding:0,fundingSide:-.004,liq:90},now-3600000)];render();});
 assert((await page.locator('#positions').textContent()).includes('Hold gain'));assert.equal(await page.locator('#positions small b.positive').count(),1,'holding credit green');
 await page.evaluate(()=>{marketFees[0]={feePct:.02,borrowHourly:.001,fundLongHourly:.002,fundShortHourly:-.004,at:Date.now()};const l=paperCosts(0,true),s=paperCosts(0,false);if(l.fee!==.02||l.fundingSide!==.002||s.fundingSide!==-.004)throw Error('Polygon per-side rates not used');delete marketFees[0];});
 await page.click('#settings');assert.equal(await page.locator('#config').evaluate(el=>el.open),true);await page.click('#closeConfig');assert.equal(await page.locator('#config').evaluate(el=>el.open),false);
 // Android bridge exists but background monitor is off: foreground recovery must still connect.
 const nativePage=await browser.newPage({viewport:{width:393,height:852}});nativePage.on('pageerror',e=>errors.push(e.message));await nativePage.route('https://**/*',r=>r.abort());
 await nativePage.addInitScript(()=>{let book={cash:100,positions:[],history:[]},quotes={},times={},indexes={},indexTimes={};window.nativeFrames=0;window.WebSocket=class{constructor(url){this.readyState=1;this.url=url;if(url.includes('backend-pricing'))setTimeout(()=>this.onmessage?.({data:JSON.stringify({m:[0,84610,1,2682],i:[0,84612,1,2683],t:Date.now()})}),100)}close(){this.readyState=3}send(){}};window.Feed={seed(raw){book=JSON.parse(raw)},paper(){return JSON.stringify(book)},snapshot(){return JSON.stringify({running:false,keepAlive:false,status:'Monitoring stopped',prices:[quotes[0]||0,quotes[1]||0],times:[times[0]||0,times[1]||0],indexPrices:indexes,indexTimes,candles:[[],[]]})},acceptPriceFrame(raw){const f=JSON.parse(raw);nativeFrames++;for(let k=0;k<f.m.length;k+=2){quotes[f.m[k]]=f.m[k+1];times[f.m[k]]=f.t}for(let k=0;k<f.i.length;k+=2){indexes[f.i[k]]=f.i[k+1];indexTimes[f.i[k]]=f.t}return 4},open(pair,long,percent,lev,costs){if(!quotes[pair]||Date.now()-times[pair]>=5000)return 'Waiting for fresh Gains price';const amount=book.cash*percent/100;book.positions.push({id:'native-test',pair,long,amount,lev,entry:quotes[pair],cost:JSON.parse(costs),kind:'paper',opened:Date.now()});book.cash-=amount;return 'OK'}};});
 await nativePage.goto('file://'+path.resolve('dist/TwinTrade.html'));await nativePage.waitForTimeout(700);assert.equal(await nativePage.locator('#price').textContent(),'$84610.00','bridge with background off recovers foreground prices');assert.equal(await nativePage.evaluate(()=>nativeFrames),1,'foreground frame reaches native ledger');assert.equal(await nativePage.locator('#keepAlive').isChecked(),false,'does not silently enable background monitoring');await nativePage.click('#long');await nativePage.waitForTimeout(300);assert((await nativePage.locator('#positions').textContent()).includes('L'),'native paper order uses recovered quote');await nativePage.click('#statsOpen');assert((await nativePage.locator('#statsTransport').textContent()).includes('Foreground socket connected'));await nativePage.click('#reconnectFeed');await nativePage.waitForTimeout(300);assert.equal(await nativePage.evaluate(()=>nativeFrames),2,'manual reconnect receives a replacement live frame');await nativePage.close();
 // Exercise the submenu and real OHLC aggregation at phone width.
 await page.setViewportSize({width:393,height:852});await page.click('#zoomMenu');assert.equal(await page.locator('#zoomPanel').isVisible(),true);
 await page.evaluate(()=>{window.originalFetchHistory=fetchHistoryChain;window.historyPages=0;fetchHistoryChain=async(chain,sym,from,to)=>{historyPages++;const rows=[];for(let t=Math.ceil(from/60000)*60000;t<=to;t+=60000)rows.push({t,o:85000,h:85100,l:84900,c:85010,source:'gains-history'});return {rows,chain};};});
 await page.click('[data-range="1440"]');await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>view.span),1440);assert((await page.evaluate(()=>candles[0].length))>=1440,'day preset fetches more than old 300-minute cap');assert.equal(await page.evaluate(()=>historyPages),5);
 await page.click('[data-interval="60"]');assert((await page.evaluate(()=>chartBars().length))<=25,'hour candles aggregate OHLC');
 await page.click('#zoomMax');assert.equal(await page.evaluate(()=>view.span),10);await page.click('#zoomMin');await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>view.span),10080);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'zoom submenu fits phone width');
 await page.evaluate(()=>{fetchHistoryChain=originalFetchHistory;view={span:1440,off:3,yOff:0};chartInterval=60;checkpointSession();});await page.reload();await page.waitForTimeout(800);assert.deepEqual(await page.evaluate(()=>({pair,span:view.span,off:view.off,interval:chartInterval})),{pair:0,span:1440,off:3,interval:60});assert((await page.evaluate(()=>candles[0].length))>=1440,'chart history survives recreation');
 await page.click('#zoomMenu');await page.click('#resetChart');await page.click('#zoomMenu');
 // Six close choices; current-coin selection preserves other-coin positions.
 await page.evaluate(()=>{const now=Date.now(),cost={fee:.035,slip:0,borrow:.07,funding:0,liq:90};mode='paper';pair=0;prices[0]=100.2698;last[0]=now;prices[1]=100;last[1]=now;book={cash:0,positions:[Engine.open(0,true,100,200,100,cost,now-3600000),Engine.open(1,false,10,10,100,{...cost,fee:0,borrow:0},now)],history:[]};render();});
 await page.click('#closeMenu');assert.equal(await page.locator('#closeMenuDialog .close-options button').count(),6);await page.click('#closeCurrentLongs');assert.equal(await page.locator('#settlementDialog').evaluate(el=>el.open),true);assert((await page.locator('#settlementRows').textContent()).includes('Holding cost deducted'));assert((await page.locator('#settlementRows').textContent()).includes('$14.00'));assert((await page.locator('#settlementRows').textContent()).includes('$7.00'));assert((await page.locator('#settlementTotal').textContent()).includes('$125.96'));assert.equal(await page.evaluate(()=>book.positions.length),1);assert.equal(await page.evaluate(()=>book.positions[0].pair),1);
 await page.waitForTimeout(4200);assert.equal(await page.locator('#settlementDialog').evaluate(el=>el.open),true,'receipt persists until dismissed');
 for(const [w,h]of [[360,640],[740,360],[393,852]]){await page.setViewportSize({width:w,height:h});const b=await page.locator('#settlementDialog').boundingBox();assert(b.x>=0&&b.y>=0&&b.x+b.width<=w+1&&b.y+b.height<=h+1,'receipt dialog fits rotated phone');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 await page.screenshot({path:'build/settlement-qa.png'});await page.click('#dismissSettlement');assert.equal(await page.locator('#settlementDialog').evaluate(el=>el.open),false);
 await page.screenshot({path:'build/mobile-qa.png'});assert.deepEqual(errors,[]);console.log('PASS: standalone HTML loads, paper long renders, settings works, repeated portrait/landscape rotations keep controls inside viewport, no script errors or horizontal overflow.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
