const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const errors=[];const page=await browser.newPage({viewport:{width:393,height:852}});page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>{window.WebSocket=class{constructor(url){this.readyState=1;this.url=url;if(url.includes('backend-pricing'))setTimeout(()=>this.onmessage?.({data:JSON.stringify({m:[0,84610,1,2682,300,84610,313,2682],i:[0,84612,1,2683],t:Date.now()})}),500)}close(){this.readyState=3}send(){}};});
 await page.goto('file://'+path.resolve('dist/TwinTrade.html'));await page.waitForTimeout(1100);
 assert.equal(await page.locator('#price').textContent(),'$84610.00');await page.click('#long');await page.waitForTimeout(300);assert((await page.locator('#positions').textContent()).includes('LONG'));
 for(const [w,h]of [[393,852],[852,393],[360,640],[740,360],[393,852]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(150);for(const id of ['menu','settings','long','short']){const b=await page.locator('#'+id).boundingBox();assert(b&&b.x>=0&&b.y>=0&&b.x+b.width<=w+1&&b.y+b.height<=h+1,`${id} outside ${w}x${h}: ${JSON.stringify(b)}`)}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No horizontal overflow');}
 await page.click('#settings');assert.equal(await page.locator('#config').evaluate(el=>el.open),true);await page.click('#closeConfig');assert.equal(await page.locator('#config').evaluate(el=>el.open),false);
 await page.screenshot({path:'build/mobile-qa.png'});assert.deepEqual(errors,[]);console.log('PASS: standalone HTML loads, paper long renders, settings works, repeated portrait/landscape rotations keep controls inside viewport, no script errors or horizontal overflow.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
