const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const nodes={},labels=[];const canvas=new Proxy({fillText:(s,x,y)=>labels.push({s,y}),measureText:s=>({width:s.length*5})},{get:(o,k)=>o[k]||(()=>{})});
const node=id=>nodes[id]??={value:({amount:'10',lev:'500'})[id]||'',checked:true,hidden:true,options:[],textContent:'',innerHTML:'',getBoundingClientRect:()=>({width:393,height:400}),getContext:()=>canvas,addEventListener(){},setAttribute(){},showModal(){this.open=true},close(){this.open=false}};
const env={console,document:{getElementById:node,querySelector:()=>node('dismiss'),querySelectorAll:()=>[],addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},setTimeout:()=>0,clearTimeout(){},setInterval(){},devicePixelRatio:1,confirm:()=>false,addEventListener(){},WebSocket:class{constructor(){this.readyState=1}close(){this.readyState=3}},ethers:{providers:{JsonRpcProvider:class{async getNetwork(){throw Error('offline')}}},Contract:class{}},AbortController,fetch:async()=>{throw Error('offline')},GABI:[]};env.window=env;vm.createContext(env);const run=c=>vm.runInContext(c,env);
for(const f of ['config.js','engine.js','trade-state.js','app.js'])run(fs.readFileSync(path.join(__dirname,'../app/src/main/assets',f),'utf8'));
(async()=>{
 await new Promise(r=>setImmediate(r));node('lev').value='500';node('lev').options=[{value:'200'},{value:'500'}];node('amount').value='100';
 run("pair=0;cfg={...cfg,fee:0,slip:0,borrow:0,funding:0};marketFees[300]={feePct:0,spreadPct:0};prices[0]=prices[300]=100;last[0]=last[300]=Date.now();book={cash:100,positions:[],history:[]};");
 // Selecting 500x and pressing Long immediately must await the same DEGEN request.
 let finish,calls=0;env.fetchJson=async u=>{calls++;assert(u.includes('/3/300?chainId=137'));return new Promise(r=>finish=r)};
 const rates=run('fetchHoldingRates(300)'),order=run('sendOrder(true)');await run('sendOrder(true)');assert.equal(calls,1);assert.equal(run('book.positions.length'),0);assert.equal(run('busy'),true);
 finish([{borrowingFeeV2HourlyRate:.00001,fundingFeeLongHourlyRate:.00002,fundingFeeShortHourlyRate:-.00004}]);await rates;await order;
 assert.equal(run('book.positions.length'),1);assert.equal(run('book.positions[0].pair'),300);assert.equal(run('book.positions[0].cost.borrow'),.001);assert.equal(run('book.positions[0].cost.fundingSide'),.002);
 const long=run('book.positions[0]');const E=env.Engine;assert(Math.abs(E.value(long,100,long.opened+3600000).hold-1.5)<1e-10);run('book.cash=100;render()');assert(node('quote').textContent.includes('L hold $1.50/h cost (1.5000% collateral/h)'));assert(node('quote').textContent.includes('S hold $1.50/h credit'));assert(node('positions').innerHTML.includes('Polygon market rate saved at entry'));
 run('book={cash:100,positions:[],history:[]};last[300]=Date.now()');await run('sendOrder(false)');const short=run('book.positions[0]');assert(Math.abs(E.value(short,100,short.opened+3600000).hold+1.5)<1e-10);const closed=E.settle(short,100,short.opened+3600000);assert(Math.abs(closed.payout-101.5)<1e-10);
 // The Android bridge receives the side's saved market rate, not BTC/fallback rates.
 let cost;env.Feed={open:(pi,long,percent,lev,c)=>{assert.equal(pi,300);assert.equal(lev,500);cost=JSON.parse(c);return 'fixture stop'},paper:()=>JSON.stringify({cash:100,positions:[],history:[]}),snapshot:()=>JSON.stringify({prices:[],candles:[]})};run('book={cash:100,positions:[],history:[]};last[300]=Date.now()');await run('sendOrder(false)');assert.equal(cost.fundingSide,-.004);assert.equal(cost.borrow,.001);delete env.Feed;
 // Tiny rates must survive loading; null/missing fields must not be interpreted as zero.
 env.fetchJson=async()=>[{borrowingFeeHourlyRate:1e-12,fundingFeeLongHourlyRate:0,fundingFeeShortHourlyRate:0}];await run('fetchHoldingRates(300)');assert.equal(run('marketFees[300].borrowHourly'),1e-10);const saved=run('marketFees[300].at');env.fetchJson=async()=>[{borrowingFeeV2HourlyRate:0,fundingFeeLongHourlyRate:null,fundingFeeShortHourlyRate:0}];assert.equal(await run('fetchHoldingRates(300)'),false);assert.equal(run('marketFees[300].at'),saved);
 // Changing order context or losing the execution quote while rates load aborts the order.
 run('marketFees[300].at=0;book={cash:100,positions:[],history:[]};last[300]=Date.now()');env.fetchJson=async()=>new Promise(r=>finish=r);const changed=run('sendOrder(true)');run('pair=1');finish([{borrowingFeeV2HourlyRate:0,fundingFeeLongHourlyRate:0,fundingFeeShortHourlyRate:0}]);await changed;assert.equal(run('book.positions.length'),0);assert.equal(run('busy'),false);
 run('pair=0;marketFees[300].at=0;last[300]=Date.now()');const stale=run('sendOrder(true)');run('last[300]=Date.now()-6000');finish([{borrowingFeeV2HourlyRate:0,fundingFeeLongHourlyRate:0,fundingFeeShortHourlyRate:0}]);await stale;assert.equal(run('book.positions.length'),0);
 env.fetchJson=async()=>{throw Error('offline')};run('last[300]=Date.now();marketFees[300].at=0');await run('sendOrder(true)');assert.equal(run('book.positions.length'),1);assert(run('book.positions[0].cost.holdingSource').includes('market rates unavailable'));
 // Live DEGEN PnL includes legacy borrowing plus v10 borrowing, as the SDK does.
 env.ethers.BigNumber=require('../app/src/main/assets/ethers.js').BigNumber;env.ethers.utils=require('../app/src/main/assets/ethers.js').utils;const B=env.ethers.BigNumber;
 const position={pair:300,index:7,long:false,raw:{collateralIndex:3,collateralAmount:B.from(100000000),leverage:B.from(500000)}};env.feePosition=position;let legacyCalls=0,currentCalls=0;
 env.feeContract={getTradeBorrowingFee:async input=>{legacyCalls++;assert.equal(input.pairIndex,300);assert.equal(input.index,7);assert.equal(input.long,false);assert(input.leverage.eq(500000));assert(input.collateral.eq(100000000));return B.from(2500000)},getTradeBorrowingFeesCollateral:async(addr,index,price)=>{currentCalls++;assert.equal(index,7);return B.from(1500000)}};
 const fees=await run("readLiveBorrowingFees(feeContract,'fixture',feePosition,100)");assert(fees.eq(4000000));assert.equal(position.borrowLegacy,2.5);assert.equal(position.borrowV10,1.5);assert.equal(legacyCalls,1);assert.equal(currentCalls,1);
 env.feeContract.getTradeBorrowingFee=async()=>{throw Error('legacy unavailable')};await assert.rejects(()=>run("readLiveBorrowingFees(feeContract,'fixture',feePosition,100)"),/legacy unavailable/);
 console.log('PASS: 500x side-specific holding dollars, credits and settlement; wait/coalesce DEGEN rates, native bridge parity, precise/invalid rates, context and stale quote guards, explicit offline assumptions.');
})().catch(e=>{console.error(e);process.exit(1)});
