package com.twintrade.app;
import android.content.*;import org.json.*;import java.util.*;
/** One synchronized owner of prices, candles and the paper ledger, shared by UI and foreground service. */
public final class MarketStore {
 private static Context context;private static JSONObject book;private static long saved=0;
 private static final TreeMap<Long,JSONObject> btc=new TreeMap<>(),eth=new TreeMap<>();
 private static final HashMap<Integer,TreeMap<Long,JSONObject>> extra=new HashMap<>();
 private static final HashMap<Integer,Double> indexPrices=new HashMap<>();
 private static final HashMap<Integer,Long> indexTimes=new HashMap<>();
 public static synchronized void indexTick(int pair,double value,long time){if(pair<0||pair>1000||!Double.isFinite(value)||value<=0||time<=0||time>System.currentTimeMillis()||time<indexTimes.getOrDefault(pair,0L))return;indexPrices.put(pair,value);indexTimes.put(pair,time);}
 private static final HashMap<Integer,Double> xprices=new HashMap<>();
 private static final HashMap<Integer,Long> xtimes=new HashMap<>();
 public static synchronized double priceOf(int pair){return pair==0?prices[0]:pair==1?prices[1]:xprices.getOrDefault(pair,0.0);}
 public static synchronized long timeOf(int pair){return pair==0?times[0]:pair==1?times[1]:xtimes.getOrDefault(pair,0L);}
 private static final HashMap<Integer,Double> caps=new HashMap<>();
 public static synchronized void updateCaps(String raw){try{JSONArray a=new JSONArray(raw);HashMap<Integer,Double> next=new HashMap<>();for(int i=0;i<a.length();i++){JSONObject m=a.getJSONObject(i);int pair=m.getInt("pairIndex");double cap=m.getDouble("maxLeverage");if(pair>=0&&pair<=1000&&Double.isFinite(cap)&&cap>=0)next.put(pair,cap);}caps.clear();caps.putAll(next);}catch(Exception ignored){}}
 private static double maxLev(int pair){return caps.getOrDefault(pair,pair==0?200.0:(pair==1||pair==300||pair==313||pair==327)?500.0:0.0);}
 private static void validateCost(JSONObject c)throws JSONException{if(c.has("fundingSide")&&!Double.isFinite(c.getDouble("fundingSide")))throw new JSONException("Invalid side funding rate");for(String k:new String[]{"fee","slip","borrow","funding","liq"})if(!Double.isFinite(c.getDouble(k)))throw new JSONException("Invalid cost assumptions");if(c.getDouble("fee")<0||c.getDouble("slip")<0||c.getDouble("slip")>=100||c.getDouble("borrow")<0||c.getDouble("liq")<=0||c.getDouble("liq")>100)throw new JSONException("Cost assumptions outside allowed range");}
 private static boolean validOhlc(double o,double h,double l,double c){return Double.isFinite(o)&&Double.isFinite(h)&&Double.isFinite(l)&&Double.isFinite(c)&&l>0&&h>=Math.max(o,c)&&l<=Math.min(o,c)&&h>=l;}
 private static boolean fresh(int pair,long now){long t=timeOf(pair);return priceOf(pair)>0&&t>0&&t<=now&&now-t<5000;}

 private static final double[] prices={0,0};private static final long[] times={0,0};
 static volatile String status="Starting monitor",historyStatus="Loading Gains history";static volatile boolean running=false;
 public static synchronized void init(Context c){if(context!=null)return;context=c.getApplicationContext();try{String raw=context.getSharedPreferences("market",0).getString("book","");if(!raw.isEmpty())book=new JSONObject(raw);JSONObject data=new JSONObject(context.getSharedPreferences("market",0).getString("candles","{}"));for(Iterator<String> it=data.keys();it.hasNext();){String key=it.next();JSONArray a=data.optJSONArray(key);if(a!=null)merge(Integer.parseInt(key),a);}}catch(Exception ignored){}}
 private static TreeMap<Long,JSONObject> map(int pair){return pair==0?btc:pair==1?eth:extra.computeIfAbsent(pair,k->new TreeMap<>());}
 public static synchronized void seed(String raw){try{if(book==null){book=new JSONObject(raw);save(true);}}catch(Exception ignored){}}
 public static synchronized String book(){try{if(book==null)book=new JSONObject("{\"cash\":100,\"positions\":[],\"history\":[]}");return book.toString();}catch(Exception e){return "{}";}}
 public static synchronized void tick(int pair,double price,long now){if(pair<0||pair>1000||!Double.isFinite(price)||price<=0||now<=0||now>System.currentTimeMillis()||now<timeOf(pair))return;if(pair<2){prices[pair]=price;times[pair]=now;}else{xprices.put(pair,price);xtimes.put(pair,now);}long t=now/60000*60000;try{TreeMap<Long,JSONObject> m=map(pair);JSONObject candle=m.get(t);if(candle==null||"gap-fill".equals(candle.optString("source"))){candle=new JSONObject().put("t",t).put("o",price).put("h",price).put("l",price).put("c",price).put("source","gains-live");m.put(t,candle);fillGaps(m);}else{candle.put("source","gains-live");candle.put("h",Math.max(candle.getDouble("h"),price)).put("l",Math.min(candle.getDouble("l"),price)).put("c",price);}while(m.size()>600)m.pollFirstEntry();if(book!=null){JSONArray ps=book.getJSONArray("positions");for(int j=ps.length()-1;j>=0;j--){JSONObject p=ps.getJSONObject(j);if(p.getInt("pair")==pair&&value(p,price,now)<=-p.getDouble("amount")*p.getJSONObject("cost").getDouble("liq")/100)closeAt(p,price,now,"Liquidated");}}save(false);}catch(Exception ignored){}}
 public static synchronized void merge(int pair,JSONArray a)throws JSONException {TreeMap<Long,JSONObject> m=map(pair);for(int i=0;i<a.length();i++){JSONObject c=a.getJSONObject(i);if(!validOhlc(c.getDouble("o"),c.getDouble("h"),c.getDouble("l"),c.getDouble("c")))continue;long t=c.getLong("t");if(t>=1000000000L&&t<1000000000000L)t*=1000;t=t/60000*60000;c.put("t",t);if(t<=0||t>System.currentTimeMillis())continue;if(!m.containsKey(t)||"gap-fill".equals(m.get(t).optString("source"))||"gains-history".equals(c.optString("source"))&&t<System.currentTimeMillis()/60000*60000||!"gains-live".equals(m.get(t).optString("source")))m.put(t,c);}fillGaps(m);while(m.size()>600)m.pollFirstEntry();}
 private static void fillGaps(TreeMap<Long,JSONObject> m)throws JSONException {m.entrySet().removeIf(e->"gap-fill".equals(e.getValue().optString("source")));if(m.isEmpty())return;long floor=m.lastKey()-599*60000L;Long prev=null;double close=0;for(Long t:new ArrayList<Long>(m.keySet())){if(prev!=null)for(long k=Math.max(prev+60000L,floor);k<t;k+=60000L)m.put(k,new JSONObject().put("t",k).put("o",close).put("h",close).put("l",close).put("c",close).put("source","gap-fill"));close=m.get(t).getDouble("c");prev=t;}while(m.size()>600)m.pollFirstEntry();}
 public static synchronized void seedOhlc(int pair,double o,double h,double l,double close,long now){if(pair<0||pair>1000||!validOhlc(o,h,l,close)||now<=0||now>System.currentTimeMillis())return;try{long t=now/60000*60000;TreeMap<Long,JSONObject> m=map(pair);JSONObject c=m.get(t);if(c==null||!"gains-live".equals(c.optString("source")))m.put(t,new JSONObject().put("t",t).put("o",o).put("h",h).put("l",l).put("c",close).put("source","gains-charts"));fillGaps(m);while(m.size()>600)m.pollFirstEntry();}catch(Exception ignored){}}
 public static synchronized String snapshot(){try{JSONObject xp=new JSONObject(),xt=new JSONObject(),xc=new JSONObject();for(Map.Entry<Integer,Double> e:xprices.entrySet())xp.put(""+e.getKey(),e.getValue());for(Map.Entry<Integer,Long> e:xtimes.entrySet())xt.put(""+e.getKey(),e.getValue());for(Map.Entry<Integer,TreeMap<Long,JSONObject>> e:extra.entrySet())xc.put(""+e.getKey(),new JSONArray(e.getValue().values()));JSONObject ip=new JSONObject(),it=new JSONObject();for(Map.Entry<Integer,Double> e:indexPrices.entrySet())ip.put(""+e.getKey(),e.getValue());for(Map.Entry<Integer,Long> e:indexTimes.entrySet())it.put(""+e.getKey(),e.getValue());return new JSONObject().put("indexPrices",ip).put("indexTimes",it).put("pricesByPair",xp).put("timesByPair",xt).put("candlesByPair",xc).put("prices",new JSONArray(prices)).put("times",new JSONArray(times)).put("candles",new JSONArray().put(new JSONArray(btc.values())).put(new JSONArray(eth.values()))).put("status",status).put("history",historyStatus).put("running",running).toString();}catch(Exception e){return "{}";}}
 public static synchronized void save(boolean force){if(context==null||(!force&&System.currentTimeMillis()-saved<5000))return;saved=System.currentTimeMillis();JSONObject c=new JSONObject();try{c.put("0",new JSONArray(btc.values())).put("1",new JSONArray(eth.values()));for(Map.Entry<Integer,TreeMap<Long,JSONObject>> x:extra.entrySet())c.put(""+x.getKey(),new JSONArray(x.getValue().values()));SharedPreferences.Editor e=context.getSharedPreferences("market",0).edit().putString("candles",c.toString());if(book!=null)e.putString("book",book.toString());if(force)e.commit();else e.apply();}catch(Exception ignored){}}
 private static double value(JSONObject p,double price,long now)throws JSONException {JSONObject c=p.getJSONObject("cost");double n=p.getDouble("amount")*p.getDouble("lev"),d=p.getBoolean("long")?1:-1,exit=price*(1-d*c.getDouble("slip")/100),rate=c.getDouble("borrow")+(c.has("fundingSide")?c.getDouble("fundingSide"):d*c.getDouble("funding"));return n*d*(exit/p.getDouble("entry")-1)-n*c.getDouble("fee")/50-n*rate/100*Math.max(0,now-p.getLong("opened"))/3600000.;}
 private static void closeAt(JSONObject p,double price,long now,String reason)throws JSONException {double amount=p.getDouble("amount"),net=Math.max(-amount,value(p,price,now));JSONArray old=book.getJSONArray("positions"),next=new JSONArray();for(int i=0;i<old.length();i++)if(!old.getJSONObject(i).getString("id").equals(p.getString("id")))next.put(old.getJSONObject(i));book.put("positions",next).put("cash",book.getDouble("cash")+Math.max(0,amount+net));p.put("net",net).put("exit",price).put("closed",now).put("status",reason);JSONArray h=new JSONArray().put(p),previous=book.getJSONArray("history");for(int i=0;i<Math.min(199,previous.length());i++)h.put(previous.get(i));book.put("history",h);save(true);}
 public static synchronized String open(int pair,boolean isLong,double percent,double leverage,String costs){try{book();long now=System.currentTimeMillis();if(pair<0||pair>1000||!fresh(pair,now))throw new Exception("Waiting for fresh Gains price");if(!Double.isFinite(percent)||percent<=0||percent>100||!Double.isFinite(leverage)||leverage<1||leverage>maxLev(pair))throw new Exception("Invalid percentage or leverage");double amount=Math.floor(book.getDouble("cash")*percent/100*1e6)/1e6;if(amount<=0)throw new Exception("No available paper collateral. Respawn to $100.");JSONObject c=new JSONObject(costs);validateCost(c);JSONObject p=new JSONObject().put("id","p"+UUID.randomUUID()).put("pair",pair).put("long",isLong).put("amount",amount).put("lev",leverage).put("entry",priceOf(pair)*(1+(isLong?1:-1)*c.getDouble("slip")/100)).put("opened",now).put("cost",c).put("status","Paper open").put("kind","paper");if(value(p,priceOf(pair),now)<=-amount*c.getDouble("liq")/100)throw new Exception("Entry costs would liquidate this position");book.getJSONArray("positions").put(p);book.put("cash",book.getDouble("cash")-amount);save(true);return "OK";}catch(Exception e){return e.getMessage();}}
 public static synchronized String close(String id){try{JSONArray ps=new JSONObject(book()).getJSONArray("positions");for(int i=0;i<ps.length();i++){JSONObject p=ps.getJSONObject(i);if(id.equals(p.getString("id"))){int pair=p.getInt("pair");if(!fresh(pair,System.currentTimeMillis()))throw new Exception("Waiting for fresh Gains price");closeAt(p,priceOf(pair),System.currentTimeMillis(),"Closed");return "OK";}}return "Position already closed";}catch(Exception e){return e.getMessage();}}
 public static synchronized void reset(){try{book=new JSONObject("{\"cash\":100,\"positions\":[],\"history\":[]}");save(true);}catch(Exception ignored){}}
}
