package com.twintrade.app;
import android.content.*;import org.json.*;import java.util.*;
/** One synchronized owner of prices, candles and the paper ledger, shared by UI and foreground service. */
public final class MarketStore {
 private static Context context;private static JSONObject book;private static long saved=0;
 private static final TreeMap<Long,JSONObject> btc=new TreeMap<>(),eth=new TreeMap<>();
 private static final double[] prices={0,0};private static final long[] times={0,0};
 static volatile String status="Starting monitor",historyStatus="Loading Gains history";static volatile boolean running=false;
 public static synchronized void init(Context c){if(context!=null)return;context=c.getApplicationContext();try{String raw=context.getSharedPreferences("market",0).getString("book","");if(!raw.isEmpty())book=new JSONObject(raw);JSONObject data=new JSONObject(context.getSharedPreferences("market",0).getString("candles","{}"));for(int i=0;i<2;i++){JSONArray a=data.optJSONArray(""+i);if(a!=null)merge(i,a);}}catch(Exception ignored){}}
 private static TreeMap<Long,JSONObject> map(int pair){return pair==0?btc:eth;}
 public static synchronized void seed(String raw){try{if(book==null){book=new JSONObject(raw);save(true);}}catch(Exception ignored){}}
 public static synchronized String book(){try{if(book==null)book=new JSONObject("{\"cash\":100,\"positions\":[],\"history\":[]}");return book.toString();}catch(Exception e){return "{}";}}
 public static synchronized void tick(int pair,double price,long now){if(pair<0||pair>1||!Double.isFinite(price)||price<=0)return;prices[pair]=price;times[pair]=now;long t=now/60000*60000;try{TreeMap<Long,JSONObject> m=map(pair);JSONObject candle=m.get(t);if(candle==null){candle=new JSONObject().put("t",t).put("o",price).put("h",price).put("l",price).put("c",price).put("source","gains-live");m.put(t,candle);}else{candle.put("h",Math.max(candle.getDouble("h"),price)).put("l",Math.min(candle.getDouble("l"),price)).put("c",price);}while(m.size()>600)m.pollFirstEntry();if(book!=null){JSONArray ps=book.getJSONArray("positions");for(int j=ps.length()-1;j>=0;j--){JSONObject p=ps.getJSONObject(j);if(p.getInt("pair")==pair&&value(p,price,now)<=-p.getDouble("amount")*p.getJSONObject("cost").getDouble("liq")/100)closeAt(p,price,now,"Liquidated");}}save(false);}catch(Exception ignored){}}
 public static synchronized void merge(int pair,JSONArray a)throws JSONException {TreeMap<Long,JSONObject> m=map(pair);for(int i=0;i<a.length();i++){JSONObject c=a.getJSONObject(i);long t=c.getLong("t");if(!m.containsKey(t)||!"gains-live".equals(m.get(t).optString("source")))m.put(t,c);}while(m.size()>600)m.pollFirstEntry();}
 public static synchronized String snapshot(){try{return new JSONObject().put("prices",new JSONArray(prices)).put("times",new JSONArray(times)).put("candles",new JSONArray().put(new JSONArray(btc.values())).put(new JSONArray(eth.values()))).put("status",status).put("history",historyStatus).put("running",running).toString();}catch(Exception e){return "{}";}}
 public static synchronized void save(boolean force){if(context==null||(!force&&System.currentTimeMillis()-saved<5000))return;saved=System.currentTimeMillis();JSONObject c=new JSONObject();try{c.put("0",new JSONArray(btc.values())).put("1",new JSONArray(eth.values()));SharedPreferences.Editor e=context.getSharedPreferences("market",0).edit().putString("candles",c.toString());if(book!=null)e.putString("book",book.toString());if(force)e.commit();else e.apply();}catch(Exception ignored){}}
 private static double value(JSONObject p,double price,long now)throws JSONException {JSONObject c=p.getJSONObject("cost");double n=p.getDouble("amount")*p.getDouble("lev"),d=p.getBoolean("long")?1:-1,exit=price*(1-d*c.getDouble("slip")/100),rate=c.getDouble("borrow")+d*c.getDouble("funding");return n*d*(exit/p.getDouble("entry")-1)-n*c.getDouble("fee")/50-n*rate/100*Math.max(0,now-p.getLong("opened"))/3600000.;}
 private static void closeAt(JSONObject p,double price,long now,String reason)throws JSONException {double amount=p.getDouble("amount"),net=Math.max(-amount,value(p,price,now));JSONArray old=book.getJSONArray("positions"),next=new JSONArray();for(int i=0;i<old.length();i++)if(!old.getJSONObject(i).getString("id").equals(p.getString("id")))next.put(old.getJSONObject(i));book.put("positions",next).put("cash",book.getDouble("cash")+Math.max(0,amount+net));p.put("net",net).put("exit",price).put("closed",now).put("status",reason);JSONArray h=new JSONArray().put(p),previous=book.getJSONArray("history");for(int i=0;i<Math.min(199,previous.length());i++)h.put(previous.get(i));book.put("history",h);save(true);}
 public static synchronized String open(int pair,boolean isLong,double percent,double leverage,String costs){try{book();long now=System.currentTimeMillis();if(pair<0||pair>1||now-times[pair]>5000||prices[pair]<=0)throw new Exception("Waiting for fresh Gains price");if(!Double.isFinite(percent)||percent<=0||percent>100||!Double.isFinite(leverage)||leverage<1||leverage>(pair==0?200:500))throw new Exception("Invalid percentage or leverage");double amount=Math.floor(book.getDouble("cash")*percent/100*1e6)/1e6;if(amount<=0)throw new Exception("No available paper collateral. Respawn to $100.");JSONObject c=new JSONObject(costs);JSONObject p=new JSONObject().put("id","p"+UUID.randomUUID()).put("pair",pair).put("long",isLong).put("amount",amount).put("lev",leverage).put("entry",prices[pair]*(1+(isLong?1:-1)*c.getDouble("slip")/100)).put("opened",now).put("cost",c).put("status","Paper open").put("kind","paper");if(value(p,prices[pair],now)<=-amount*c.getDouble("liq")/100)throw new Exception("Entry costs would liquidate this position");book.getJSONArray("positions").put(p);book.put("cash",book.getDouble("cash")-amount);save(true);return "OK";}catch(Exception e){return e.getMessage();}}
 public static synchronized String close(String id){try{JSONArray ps=new JSONObject(book()).getJSONArray("positions");for(int i=0;i<ps.length();i++){JSONObject p=ps.getJSONObject(i);if(id.equals(p.getString("id"))){int pair=p.getInt("pair");if(System.currentTimeMillis()-times[pair]>5000)throw new Exception("Waiting for fresh Gains price");closeAt(p,prices[pair],System.currentTimeMillis(),"Closed");return "OK";}}return "Position already closed";}catch(Exception e){return e.getMessage();}}
 public static synchronized void reset(){try{book=new JSONObject("{\"cash\":100,\"positions\":[],\"history\":[]}");save(true);}catch(Exception ignored){}}
}
