package com.twintrade.app;
import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.os.*;import org.java_websocket.client.WebSocketClient;import org.java_websocket.handshake.ServerHandshake;import org.json.*;import java.net.*;import java.io.*;import java.util.concurrent.*;
public class PriceMonitorService extends Service {
 private WebSocketClient socket;private final ScheduledExecutorService jobs=Executors.newScheduledThreadPool(2);private PowerManager.WakeLock wake;private volatile boolean stopped=false;private volatile long lastFrame=0,lastConnect=0;private volatile boolean historyBusy=false;
 public void onCreate(){super.onCreate();MarketStore.init(this);MarketStore.running=true;NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);nm.createNotificationChannel(new NotificationChannel("prices","Background market monitoring",NotificationManager.IMPORTANCE_LOW));Intent launch=new Intent(this,MainActivity.class);PendingIntent open=PendingIntent.getActivity(this,0,launch,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Intent stop=new Intent(this,PriceMonitorService.class).setAction("STOP");PendingIntent stopAction=PendingIntent.getService(this,1,stop,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(this,"prices").setContentTitle("TwinTrade is monitoring BTC and ETH").setContentText("Candles and paper positions continue in the background").setSmallIcon(android.R.drawable.ic_menu_recent_history).setContentIntent(open).setOngoing(true).addAction(new Notification.Action.Builder(null,"Stop monitoring",stopAction).build()).build();if(Build.VERSION.SDK_INT>=34)startForeground(42,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE);else startForeground(42,n);wake=((PowerManager)getSystemService(POWER_SERVICE)).newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"TwinTrade:Prices");wake.acquire();jobs.scheduleWithFixedDelay(()->{if(stopped)return;try{long now=System.currentTimeMillis();if(socket==null||socket.isClosed()||(now-lastFrame>20000&&now-lastConnect>20000)){connect();}}catch(Exception e){MarketStore.status="Reconnecting";}},0,3,TimeUnit.SECONDS);jobs.execute(this::history);}
 private synchronized void connect(){if(stopped)return;lastConnect=System.currentTimeMillis();if(socket!=null)socket.close();MarketStore.status="Connecting";try{socket=new WebSocketClient(new URI("wss://backend-pricing.eu.gains.trade/v4")){public void onOpen(ServerHandshake h){lastFrame=System.currentTimeMillis();MarketStore.status="Connected · background active";jobs.execute(()->history());}public void onMessage(String raw){if(PriceMonitorService.this.socket!=this)return;lastFrame=System.currentTimeMillis();try{JSONArray a=new JSONArray(raw);if(a.length()<=1||a.length()%2!=0)return;for(int i=0;i<a.length();i+=2){int pair=a.getInt(i);if(pair==0||pair==1)MarketStore.tick(pair,a.getDouble(i+1),lastFrame);}}catch(Exception ignored){}}public void onClose(int code,String reason,boolean remote){MarketStore.status="Disconnected · retrying";}public void onError(Exception ex){MarketStore.status="Network unavailable · retrying";}};socket.setConnectionLostTimeout(15);socket.connect();}catch(Exception e){MarketStore.status="Connection failed · retrying";}}
 private void history(){synchronized(this){if(historyBusy||stopped)return;historyBusy=true;}try{for(int pair=0;pair<2;pair++){long to=System.currentTimeMillis(),from=to-300*60000L;String url="https://api.gains.trade/v1/polygon/markets/"+(pair==0?"BTC-USD":"ETH-USD")+"/candles?interval=1m&from="+from+"&to="+to;HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(15000);try{if(c.getResponseCode()!=200)throw new IOException("HTTP "+c.getResponseCode());ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] b=new byte[8192];int count;while((count=in.read(b))!=-1)bytes.write(b,0,count);}JSONArray rows=new JSONObject(bytes.toString("UTF-8")).getJSONArray("data"),a=new JSONArray();for(int i=0;i<rows.length();i++){JSONObject r=rows.getJSONObject(i);double o=r.getDouble("open"),h=r.getDouble("high"),l=r.getDouble("low"),close=r.getDouble("close");long t=r.getLong("time");if(t>0&&t<=to&&Double.isFinite(o)&&Double.isFinite(h)&&Double.isFinite(l)&&Double.isFinite(close)&&l>0&&h>=Math.max(o,close)&&l<=Math.min(o,close))a.put(new JSONObject().put("t",t).put("o",o).put("h",h).put("l",l).put("c",close).put("source","gains-history"));}MarketStore.merge(pair,a);MarketStore.save(true);}finally{c.disconnect();}}MarketStore.historyStatus="Gains history + live · 1m";}catch(Exception e){MarketStore.historyStatus="History unavailable · cached/live candles shown";if(!stopped)jobs.schedule(this::history,30,TimeUnit.SECONDS);}finally{historyBusy=false;}}
 public int onStartCommand(Intent i,int flags,int id){if(i!=null&&"STOP".equals(i.getAction())){getSharedPreferences("market",0).edit().putBoolean("keepAlive",false).apply();stopSelf();return START_NOT_STICKY;}return START_STICKY;}
 public IBinder onBind(Intent i){return null;}
 public void onDestroy(){stopped=true;MarketStore.running=false;MarketStore.status="Monitoring stopped";if(socket!=null)socket.close();jobs.shutdownNow();MarketStore.save(true);if(wake!=null&&wake.isHeld())wake.release();super.onDestroy();}
}
